version: '3'

services:
  frontend:
    build: ./frontend
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports: 
      - 3000:3000
  api:
    build: ./api
    restart: always
    volumes:
      - ./api:/app
      - /app/node_modules
    ports: 
      - 5555:5000
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: '3306'
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: time_db
  mysql:
    image: mysql
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: time_db
  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080

volumes:
  mysql_data:
