version: '3'

services:
  frontend:
    build: ./frontend
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports: 
      - 3000:3000
    environment:
      VITE_API_URL: ${API_PORT}
  api:
    build: ./api
    restart: always
    volumes:
      - ./api:/app
      - /app/node_modules
    ports: 
      - ${API_PORT}:5000
    depends_on:
      - mysql
    env_file:
      - .api.env
  mysql:
    image: mysql
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .db.env
  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080

volumes:
  mysql_data:
